add logs

diff --git a/mac/essentials/Cellframe-Dashboard-pkginstall/postinstall b/mac/essentials/Cellframe-Dashboard-pkginstall/postinstall
--- a/mac/essentials/Cellframe-Dashboard-pkginstall/postinstall
+++ b/mac/essentials/Cellframe-Dashboard-pkginstall/postinstall
@@ -11,8 +11,8 @@ SERVICE=com.demlabs."$APP_NAME"Service.plist
 NODE=com.demlabs.cellframe-node.plist
 
 mkdir -p $DAP_PREFIX
-cp -rf /Applications/$APP_NAME.app/Contents/Resources/etc $DAP_PREFIX
-cp -rf /Applications/$APP_NAME.app/Contents/Resources/share $DAP_PREFIX
+sudo mv -f /Applications/$APP_NAME.app/Contents/Resources/etc $DAP_PREFIX
+sudo mv -f /Applications/$APP_NAME.app/Contents/Resources/share $DAP_PREFIX
 
 for filename in $(find $DAP_PREFIX | grep -v bugreport); do
     if [ -d $filename ]; then
@@ -26,7 +26,7 @@ wd=$(pwd)
 cd $EXEC_PREFIX
 
 sudo chmod +x $EXEC_PREFIX/create_configs.sh
-sudo $EXEC_PREFIX/create_configs.sh
+$EXEC_PREFIX/create_configs.sh || echo "not create config" >> /tmp/cellframe-dashboard_error.txt
 
 rm $EXEC_PREFIX/*.sh
 
@@ -38,23 +38,23 @@ done
 
 cd $wd
 
-echo $SERVICE
-sudo launchctl stop $SERVICE
-sudo launchctl unload -w /Library/LaunchDaemons/$SERVICE
+echo $SERVICE || exit $?
+sudo launchctl stop $SERVICE || true
+sudo launchctl unload -w /Library/LaunchDaemons/$SERVICE || exit $?
 
-echo $NODE
-sudo launchctl stop $NODE
-sudo launchctl unload -w /Library/LaunchDaemons/$NODE
+echo $NODE || exit $?
+sudo launchctl stop $NODE || true
+sudo launchctl unload -w /Library/LaunchDaemons/$NODE || exit $?
 
-sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE /Library/LaunchDaemons/$SERVICE
-sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$NODE /Library/LaunchDaemons/$NODE
+sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE /Library/LaunchDaemons/$SERVICE || exit $?
+sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$NODE /Library/LaunchDaemons/$NODE || exit $?
 
-sudo chown root /Library/LaunchDaemons/$SERVICE
-sudo chmod 600 /Library/LaunchDaemons/$SERVICE
-sudo chown root /Library/LaunchDaemons/$NODE
-sudo chmod 600 /Library/LaunchDaemons/$NODE
-sudo launchctl load -w /Library/LaunchDaemons/$NODE
-sudo launchctl load -w /Library/LaunchDaemons/$SERVICE
+sudo chown root /Library/LaunchDaemons/$SERVICE || exit $?
+sudo chmod 600 /Library/LaunchDaemons/$SERVICE || exit $?
+sudo chown root /Library/LaunchDaemons/$NODE || exit $?
+sudo chmod 600 /Library/LaunchDaemons/$NODE || exit $?
+sudo launchctl load -w /Library/LaunchDaemons/$NODE || exit $?
+sudo launchctl load -w /Library/LaunchDaemons/$SERVICE || exit $?
 # [ ! -e /Library/LaunchDaemons/cleanup ] && sudo cp -r /Applications/"$APP_NAME".app/Contents/resources/cleanup /Library/LaunchDaemons/
 # sudo chown -R root:wheel /Library/LaunchDaemons/cleanup
 # sudo ln -sf /Library/LaunchDaemons/cleanup/com.demlabs.cleanup.plist /Library/LaunchDaemons/com.demlabs.cleanup.plist
@@ -64,6 +64,6 @@ sudo launchctl load -w /Library/LaunchDaemons/$SERVICE
 
 
 
-sudo launchctl start $NODE
-sudo launchctl start $SERVICE
+sudo launchctl start $NODE || exit $?
+sudo launchctl start $SERVICE || exit $?
 
