testing to create agents

diff --git a/mac/essentials/Cellframe-Dashboard-pkginstall/postinstall b/mac/essentials/Cellframe-Dashboard-pkginstall/postinstall
--- a/mac/essentials/Cellframe-Dashboard-pkginstall/postinstall
+++ b/mac/essentials/Cellframe-Dashboard-pkginstall/postinstall
@@ -6,9 +6,7 @@ set -x
 sudo xattr -rd com.apple.quarantine /Applications/"$APP_NAME".app
 sudo killall -HUP mDNSResponder
 
-EXEC_PREFIX=/Applications/$APP_NAME.app/Contents/MacOS
-SERVICE=com.demlabs."$APP_NAME"Service
-NODE=com.demlabs.cellframe-node
+EXEC_PREFIX=/Applications/$APP_NAME.app/Contents/Resources
 
 mkdir -p $DAP_PREFIX
 sudo mv -f /Applications/$APP_NAME.app/Contents/Resources/etc $DAP_PREFIX
@@ -26,36 +24,18 @@ wd=$(pwd)
 cd $EXEC_PREFIX
 
 sudo chmod +x $EXEC_PREFIX/create_configs.sh
+sudo chmod +x $EXEC_PREFIX/create_agents.sh
 sudo chmod +x $EXEC_PREFIX/create_configs_from_tpl.sh
 
-$EXEC_PREFIX/create_configs.sh 2>> /tmp/cellframe-dashboard_error.txt || { error=$?; echo "not create configs $error" >> /tmp/cellframe-dashboard_error.txt; exit $error; }
+#$EXEC_PREFIX/create_configs.sh 2>> /tmp/cellframe-dashboard_error.txt || { error=$?; echo "not create configs $error" >> /tmp/cellframe-dashboard_error.txt; exit $error; }
 
-rm $EXEC_PREFIX/*.sh
 
 for filename in $(ls . | grep -v '.'); do
 	if [ -L $filename ] && [ ! -e $filename ]; then
 		strip -u -r $filename
 	fi
 done
+exec("sudo -u user $EXEC_PREFIX/create_agents.sh")
 
+rm $EXEC_PREFIX/*.sh
 cd $wd
-
-echo $SERVICE
-sudo launchctl stop $SERVICE
-sudo launchctl unload -w ~/Library/LaunchAgents/$SERVICE.plist
-
-echo $NODE || exit $?
-sudo launchctl stop $NODE
-sudo launchctl unload -w ~/Library/LaunchAgents/$NODE
-
-ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE.plist ~/Library/LaunchAgents/$SERVICE.plist
-ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$NODE.plist ~/Library/LaunchAgents/$NODE.plist
-
-launchctl bootstrap gui/${id -u $USER} ~/Library/LaunchAgents/$NODE.plist
-echo ${id -u $USER} > /tmp/my_uid
-launchctl bootstrap gui/${id -u $USER} ~/Library/LaunchAgents/$SERVICE.plist
-
-
-launchctl start $NODE
-launchctl start $SERVICE
-
